### ISSUE TITLE
Updating to 2.13.0 breaks the build 

### ISSUE THREAD

**Issue by rprimet** [wmonk/create-react-app-typescript#244]
### Is this a bug report?
Yes

### Environment

2. `node -v`:  8.9.4
3. `npm -v`: 3.10.8

Then, specify:

1. Operating system: Linux 
2. Browser and version (if relevant): Irrelevant

### Steps to Reproduce

1. set the `react-script-ts` version of an existing project to`0.2.13`
2. run `npm install`
3. run `npm start`

### Expected Behavior
The project installs updated dependencies, then builds and starts

### Actual Behavior

- During the `npm install` phase: 

```
├─┬ react-scripts-ts@2.13.0 
│ ├─┬ tsconfig-paths-webpack-plugin@2.0.0 
│ │ ├─┬ chalk@2.3.0 
│ │ │ └── supports-color@4.5.0 
│ │ └─┬ tsconfig-paths@3.1.1 
│ │   ├── deepmerge@2.0.1 
│ │   └── strip-bom@3.0.0 
│ └── UNMET PEER DEPENDENCY typescript@^2.1.0
└── UNMET PEER DEPENDENCY typescript@2.x
```

During the `npm start` phase:

```
> react-scripts-ts start

module.js:540
    throw err;
    ^

Error: Cannot find module 'typescript'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
```

**Comment by rprimet** [comment]
OK, so this has been reported in #241 

Leaving this issue open since it is not obvious how to migrate without documentation

**Comment by DorianGrey** [comment]
Oh... yes, this only happens when updating from < 2.13.0 to 2.13.0 - `typescript` was moved to be a peer dependency of `react-scripts-ts`, which installs `typescript` as a dev dependency when initializing a new project. I'll see if I can get some instructions pushed tomorrow.

Until then:
https://github.com/wmonk/create-react-app-typescript/pull/165#issuecomment-359512965

**Comment by DorianGrey** [comment]
Added a particular section to the README: https://github.com/wmonk/create-react-app-typescript#from-2130-to-2130
